name: Car Assembly Line Pipeline

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create build directory
      run: |
        mkdir -p build
        echo "Assembly started at $(date)" > build/car_parts.txt
        echo "1. Engine: V8" >> build/car_parts.txt
        echo "2. Body: Sedan" >> build/car_parts.txt
        echo "3. Wheels: 4x Alloy" >> build/car_parts.txt
        echo "4. Interior: Leather" >> build/car_parts.txt
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: car-assembly
        path: build/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: car-assembly
        path: build/
        
    - name: Verify parts
      run: |
        echo "=== File content ==="
        cat build/car_parts.txt
        echo "=== Testing parts ==="
        grep "Engine: V8" build/car_parts.txt
        grep "Body: Sedan" build/car_parts.txt
        grep "Wheels: 4x Alloy" build/car_parts.txt
        grep "Interior: Leather" build/car_parts.txt
